{{- if .Capabilities.APIVersions.Has "route.openshift.io/v1/Route" }}
{{- $fullName := include "req2stdout.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "req2stdout.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/timeout: 24d
  name: {{ $fullName }}
spec:
  host: {{ .Values.route.web.host }}
  port:
    targetPort: web
  tls:
    {{- toYaml .Values.route.web.tls | nindent 4 }}
  to:
    kind: Service
    name: {{ $fullName }}
{{ end }}
