# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/f-w/req2stdout
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

service:
  web:
    type: ClusterIP
    port: 80

resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi

# extra environment variables. For example
# - name: TZ
#   value: America/Vancouver
extraEnvs:
  - name: TZ
    value: America/Vancouver

route:
  web:
    host: ''
    tls:
      termination: edge
  smtp:
    host: ''
